services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: php_app
    depends_on:
      - db
    volumes:
      - .:/srv
    networks:
      - bank_system_project
    environment:
      SYMFONY_ENV: dev
    ports:
      - "9000:9000"  # Expose PHP-FPM pour Nginx

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - app
    volumes:
      - .:/srv
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf  # Ajouter config Nginx
    ports:
      - "8000:80"
    environment:
      NGINX_HOST: bank_system.fr
      NGINX_PORT: 80
    networks:
      - bank_system_project

  db:
    image: mariadb:latest
    container_name: bank_system_mysql
    environment:
      MARIADB_ROOT_PASSWORD: secret
      MARIADB_DATABASE: bank_system
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - bank_system_project

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: bank_system_pma
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - "8080:80"
    networks:
      - bank_system_project

  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - bank_system_project

volumes:
  mysql-data: {}

networks:
  bank_system_project: {}